name: GHA workflow to deploy dotnet in webapp + terrafrom
on: 
  workflow_dispatch
jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v7
            - name: install dotnet
              uses: actions/setup-dotnet@v6
              with:
                  dotnet-version: 10.0.x
            - name: restore dependencies
              run: |
                cd dotnetproject1
                dotnet restore
            - name: Build dotnet
              run: |
                 cd dotnetproject1
                 dotnet build --configuration Release
